version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/ezops-test-guilhermepardo
hooks:
  ApplicationStop:
    - location: scripts/aplication_stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root