version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/ezops-test-guilhermepardo
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 3000
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 3000
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 3000
      runas: root